<?php
   $applicationData = Mage::registry('application_data');
   $applicationCode = $applicationData->getAppCode();
   
   $themeName = Mage::helper('mobiadmin')->getThemeName($applicationCode);   
   
   $theme_shopperfile = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'mobi_assets/'.'theme_files/'.$themeName.'/personalizer'.'/'.'personalizer.xml';
   $themeFileXmlData = simplexml_load_file($theme_shopperfile) or die("Error: Cannot create object");
   
   $appthemefile = Mage::getBaseDir('media').DS.'mobi_commerce'.DS.$applicationCode.DS.'personalizer/'.'personalizer.xml';   
?>
<div class="personalization entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Personalization')?></h4>
	</div>
	<div id="store_information" class="fieldset ">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
				    <input type="hidden" value="<?php echo $themeName;?>" name="themename"/>
				    <?php foreach($themeFileXmlData as $personalizatioOption => $themeOptionValue):?>
					    <tr>
						    <td class="label"><?php echo $themeOptionValue->title; ?></td>
						    <td class="value">	
							    <?php 								
								if(file_exists ($appthemefile)) {
									$issetXmlFile = simplexml_load_file($appthemefile);
									$themeCurrentValue = $issetXmlFile->$personalizatioOption->current_value;
								}else {
									$themeCurrentValue = $themeOptionValue->current_value;
								}
								?>
							    <input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][type]" value="<?php echo $themeOptionValue->type; ?>">
								<input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][title]" value="<?php echo $themeOptionValue->title; ?>">								
								<input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][css]" value="<?php echo $themeOptionValue->css; ?>">
								<input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][description]" value="<?php echo $themeOptionValue->description; ?>">
								<input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][svg_filenames]" value="<?php echo $themeOptionValue->svg_filenames; ?>">
								<input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][code_session]" value="<?php echo $themeOptionValue->code_session; ?>">
								<input type="hidden" name="personalizer[<?php echo $personalizatioOption?>][default_value]" value="<?php echo $themeOptionValue->default_value; ?>">
								<input value="<?php echo $themeCurrentValue; ?>" style="background:<?php echo $themeCurrentValue; ?>;" id="colorpickerField<?php echo $personalizatioOption?>" type="text" name="personalizer[<?php echo $personalizatioOption; ?>][current_value]">
								<small style="display:block;"><?php echo $themeOptionValue->description; ?></small>
							</td>
							<script>
							jQuery(function(){
								jQuery('#colorpickerField<?php echo $personalizatioOption ?>').ColorPicker({
								color: '<?php echo $themeOptionValue->current_value; ?>',
								onChange: function (hsb, hex, rgb) {
									jQuery('#colorpickerField<?php echo $personalizatioOption ?>').css('backgroundColor', '#' + hex);
									jQuery('#colorpickerField<?php echo $personalizatioOption ?>').val('#' + hex);
									}
								});
							})
							</script>
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
