<?php
$value = Mage::app()->getRequest()->getParam('link_type_value');
$value = explode('_', $value);
$is_checked = false;
if(isset($value[1]) && $value[1] == '1'){
	$is_checked = true;
}
?>

<div class="entry-edit">
    <div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category List')?></h4>
	</div>
	<div class="fieldset ">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
			    <tbody>
					<input id="linktype" type="hidden" name="type" value="category">
					<tr>
						<td colspan="2">
							<label for="category_force_product_nav">
							<input type="checkbox" name="category_force_product_nav" id="category_force_product_nav" <?php if($is_checked) { ?>checked="checked"<?php } ?> />
								<?php echo $this->__('Force Navigate to Product List'); ?>
							</label>
						</td>
					</tr>

					<tr>
						<td colspan="2"><div class="product-grid"><?php echo $this->getLayout()->createBlock('mobiadmin3/adminhtml_applications_grid_widget_deeplink_category')->toHtml();?></div></td>
					</tr>
			    </tbody>
			</table>
		</div>
	</div>		
</div>